---
- name: Install Kubernetes volume dependencies
  become: true
  ansible.builtin.yum:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-initiator-utils
    - nfs-utils
  when: ansible_os_family == "RedHat"

- name: "Import main tasks"
  ansible.builtin.include_tasks: common/main.yml
...
