---
- name: Install Kubernetes dependencies
  become: true
  community.general.zypper:
    name: "{{ item }}"
    state: present
  with_items:
    - iscsi-initiator-utils
    - nfs-utils
    - k3s-selinux

- name: "Import main tasks"
  ansible.builtin.include_tasks: common/main.yml
...
