---
- name: Copy K3s service file
  become: true
  ansible.builtin.template:
    src: "k3s.service.j2"
    dest: "{{ k3s_systemd_dir }}/k3s.service"
    owner: root
    group: root
    mode: 0644
  register: k3s_service

- name: Enable and check K3s service
  become: true
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: "{{ k3s_service.changed }}"
    state: started
    enabled: true
