---
- name: Enable and restart K3s service
  become: true
  ansible.builtin.systemd:
    name: k3s
    daemon_reload: true
    state: restarted
    enabled: true

- name: "Reboot host"
  become: true
  ansible.builtin.reboot:
    reboot_timeout: 600
    test_command: /usr/bin/true
    pre_reboot_delay: 5
    post_reboot_delay: 5

...
